
#' Improved fitness? Predicate.
#'
#' @description Return TRUE after the first generation or
#'              if the current fitness is higher than the 
#'              previous fitness.
#'
#' @details The vector popStat is generated by the function
#'          \code{xegaPopulation::ObservePopulation()}.    
#'          The highest fitness is in the 6th out of 9 elements
#'          of the population statistics vectors of a generation.
#'          
#'
#' @param popStat   Population statistics vector. 
#'
#' @return Boolean.
#' 
#' @examples
#' xegaDebug(debug=FALSE, msg="nothing is shown")
#' xegaDebug(debug=TRUE, msg="nothing is shown")
#' xegaDebug(debug=TRUE, msg="xegaDebug:", obj=xegaDebug)
#' @export
xegaImproved<-function(popStat)
{l<-length(popStat)
if (l<18) {return(TRUE)}
Improved<-(popStat[l-12]<popStat[l-3])
# cat("xegaImproved:",Improved," t-1(", popStat[l-12], ") t(", popStat[l-3], ")\n")  
return(Improved)
}

